apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-backend-api
  namespace: sentiment-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: sentiment-backend-api

  template:
    metadata:
      labels:
        app: sentiment-backend-api

    spec:
      nodeSelector:
        role: backend

      containers:
        - name: sentiment-backend-api
          image: 487620625686.dkr.ecr.eu-north-1.amazonaws.com/sentiment-backend:3

          ports:
            - containerPort: 8000

          env:
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: FRONTEND_URL

            - name: NEWS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: NEWS_API_KEY

          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data

      volumes:
        - name: sqlite-data
          emptyDir: {}

      imagePullSecrets:
        - name: ecr-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-backend-scheduler
  namespace: sentiment-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sentiment-backend-scheduler

  template:
    metadata:
      labels:
        app: sentiment-backend-scheduler

    spec:
      nodeSelector:
        role: backend

      containers:
        - name: sentiment-backend-scheduler
          image: 487620625686.dkr.ecr.eu-north-1.amazonaws.com/sentiment-backend:3

          command: ["python", "scheduler.py"]

          env:
            - name: NEWS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: NEWS_API_KEY

            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: FRONTEND_URL

          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data

      volumes:
        - name: sqlite-data
          emptyDir: {}

      imagePullSecrets:
        - name: ecr-secret
