apiVersion: v1
kind: Service
metadata:
  name: sentiment-backend-service
  namespace: sentiment-app

spec:
  type: NodePort

  selector:
    app: sentiment-backend-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
      protocol: TCP
