# apiVersion: v1
# kind: Service
# metadata:
#   name: sentiment-backend-service
#   namespace: sentiment-app

# spec:
#   type: ClusterIP

#   selector:
#     app: sentiment-backend-api

#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
